# backend/pyproject.toml
[tool.poetry]
name = "ha-backend"
version = "0.1.0"
description = "AI Attendance Backend"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "src", from = "."}]

[tool.poetry.dependencies]
python = "^3.14"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
motor = "^3.7.1"
pymongo = "^4.15.5"
python-dotenv = "^1.2.1"
pydantic = "^2.12.5"
email-validator = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "^0.21.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"